---
title: "modified implementation"
author: "Daniel DeCollo"
date: "2023-04-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Clean Environment
rm(list = ls())

#Import Libraries
library(ggplot2)
library(data.table)
library(dplyr)
library(xgboost)
library(ROSE)
library(pROC)
library(caret)
```

## Get data
```{r}
season_2009 <- fread('./season_2009.csv')
season_2010 <- fread('./season_2010.csv')
season_2011 <- fread('./season_2011.csv')
season_2012 <- fread('./season_2012.csv')
season_2013 <- fread('./season_2013.csv')
season_2014 <- fread('./season_2014.csv')
season_2015 <- fread('./season_2015.csv')
season_2016 <- fread('./season_2016.csv')
season_2017 <- fread('./season_2017.csv')
season_2018 <- fread('./season_2018.csv')
season_2019 <- fread('./season_2019.csv')
season_2020 <- fread('./season_2020.csv')
season_2021 <- fread('./season_2021.csv')
```

## Preprocessing - superbowl winners
```{r}
#2009
season_2009$super_bowl_winner <- 0
season_2009$super_bowl_winner[season_2009$Teams == "Steelers"] <- 1

#2010
season_2010$super_bowl_winner <- 0
season_2010$super_bowl_winner[season_2010$Teams == "Saints"] <- 1

#2011
season_2011$super_bowl_winner <- 0
season_2011$super_bowl_winner[season_2011$Teams == "Packers"] <- 1

#2012
season_2012$super_bowl_winner <- 0
season_2012$super_bowl_winner[season_2012$Teams == "Giants"] <- 1

#2013
season_2013$super_bowl_winner <- 0
season_2013$super_bowl_winner[season_2013$Teams == "Ravens"] <- 1

#2014
season_2014$super_bowl_winner <- 0
season_2014$super_bowl_winner[season_2014$Teams == "Seahawks"] <- 1

#2015
season_2015$super_bowl_winner <- 0
season_2015$super_bowl_winner[season_2015$Teams == "Patriots"] <- 1

#2016
season_2016$super_bowl_winner <- 0
season_2016$super_bowl_winner[season_2016$Teams == "Broncos"] <- 1

#2017
season_2017$super_bowl_winner <- 0
season_2017$super_bowl_winner[season_2017$Teams == "Patriots"] <- 1

#2018
season_2018$super_bowl_winner <- 0
season_2018$super_bowl_winner[season_2018$Teams == "Eagles"] <- 1

#2019
season_2019$super_bowl_winner <- 0
season_2019$super_bowl_winner[season_2019$Teams == "Patriots"] <- 1

#2020
season_2020$super_bowl_winner <- 0
season_2020$super_bowl_winner[season_2020$Teams == "Chiefs"] <- 1

#2021
season_2021$super_bowl_winner <- 0
season_2021$super_bowl_winner[season_2021$Teams == "Buccaneers"] <- 1
```

## training/ testing data
```{r}
#merge training data
training <- rbind(season_2009, season_2010, season_2011, 
                 season_2012, season_2013, season_2014)

#join 2018-2020 for testing data
testing <- rbind(season_2015, season_2016, season_2017,
                 season_2018, season_2019, season_2020)

#Validation data
validation <- season_2021
```

```{r}
training[1]
```

## drop unused columns
```{r}
training <- training[,-'Teams']

testing <- testing[,-'Teams']
```

## training size
```{r}
#number of rows that indicate winning teams
table(training$super_bowl_winner == 1)
```
## Percentage of minority observation
```{r}
sum(training$super_bowl_winner)/nrow(training)*100
```

## Oversampling for data imbalance
```{r}
#desired length of training
n_train <- 1000

#probability of minority class being generated
p_minority <- 0.5 #not bad performance for .25

rose_training <- ROSE(as.factor(super_bowl_winner) ~ ., data  = training, N = n_train, p = p_minority, seed = 412)$data
```

## New training table
```{r}
table(rose_training$super_bowl_winner == 1)
```

## train model
```{r}
original_model <- glm(super_bowl_winner ~ Wins + Loses + Ties + win_percent + total_points +
                        total_rushing_yards + total_passing_yards + total_yards, 
                      data = training, family = binomial())

#Model with ROSE Training data
rose_model <- glm(super_bowl_winner ~ Wins + Loses + Ties + win_percent + total_points +
                    total_rushing_yards + total_passing_yards + total_yards, 
                  data = rose_training, family = binomial())
```


## Model Summary
```{r}
summary(original_model)
```

```{r}
summary(rose_model)
```

## test model
Adds the probability for the team to win
```{r}
testing$prediction <- predict(original_model, newdata = testing, type = "response")

#test ROSE model
testing$rose_prediction <- predict(rose_model, newdata = testing, type = "response")
```

```{r}
#plot for original model
ggplot(testing, aes(x = reorder(prediction, prediction), y = prediction)) +
  geom_point(aes(colour = super_bowl_winner)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) +
  theme(legend.position = "none", axis.text.x = element_blank()) + 
  xlab("probability") 
```

```{r}
#plot for original model
ggplot(testing, aes(x = reorder(rose_prediction, rose_prediction), y = rose_prediction)) +
  geom_point(aes(colour = super_bowl_winner)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) +
  theme(legend.position = "none", axis.text.x = element_blank()) + 
  xlab("probability") 
```

## AUC
```{r}
auc(testing$super_bowl_winner, testing$prediction)
```

```{r}
auc(testing$super_bowl_winner, testing$rose_prediction)
```

## Confusion Matrix
Need to add loop for finding the best sensitivity https://statinfer.com/203-4-2-calculating-sensitivity-and-specificity-in-r/
```{r}
threshold=0.50
temp <- testing %>% select(super_bowl_winner)
temp$predicted_values <- ifelse(testing$prediction>threshold,1,0)
temp$rose_predicted_values <- ifelse(testing$rose_prediction>threshold,1,0)

original_conf_matrix<-table(temp$predicted_values, temp$super_bowl_winner)
rose_conf_matrix<-table(temp$rose_predicted_values, temp$super_bowl_winner)

original_conf_matrix
rose_conf_matrix
```

## Validation
```{r}
validation$prediction <- predict(original_model, newdata = validation, type = "response")

#test ROSE model
validation$rose_prediction <- predict(rose_model, newdata = validation, type = "response")
```

```{r}
ggplot(validation, aes(x = reorder(Teams, prediction), y = prediction)) +
  geom_point(aes(colour = Teams)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) +
  theme(legend.position = "none") + 
  xlab("NFL Teams") + 
  ylab("Predicted Winner") + 
  ggtitle("2021 Super Bowl Winner Prediction")
```

```{r}
ggplot(validation, aes(x = reorder(Teams, rose_prediction), y = rose_prediction)) +
  geom_point(aes(colour = Teams)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) +
  theme(legend.position = "none") + 
  xlab("NFL Teams") + 
  ylab("Predicted Winner") + 
  ggtitle("2021 Super Bowl Winner Prediction")
```



